version: "3.9"

services:
  app:
    build: .
    container_name: resume_app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres_password
      DB_NAME: resume_db
      JWT_SECRET: extremely_long_jwt_secret_for_security_passed_32_characters
      ENCRYPTION_KEY: extremely_long_encryption_key_for_mfa_passed_32_characters
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - db
      - redis
      - kafka
    restart: always
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: resume_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: resume_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    container_name: resume_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: resume_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: resume_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network: